name: MinecraftScriptPlugin
main: com.qvolcano.mcsp.MinecraftScriptPlugin
version: 1.0.0
mscp:
  description: MinecraftScriptPlugin command.
  usage: /<command> [player]
  permission: <plugin name>
  permission-message: You don't have <permission></source> </code> </blockquote> 